server:
  port: 8800
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://120.48.151.75:3306/hxp-blog?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hxp123
  redis:
    host: 8.130.124.184
    port: 7679
    timeout: 3000
    database: 8
    password: vDZ6Ir]GFo


#==============================knife4j配置==============================
knife4j:
  enable: true
  basic:
    enable: true
    username: test
    password: 123456
  openapi:
    title: 学鹏代码小站接口文档
    description: 一个专注于技术分享的博客平台
    email: 2497754747@qq.com
    concat: 学鹏
    url: http://blog.hexp.online/
    version: v1.0
    group:
      test1:
        group-name: 博客服务
        api-rule: package
        api-rule-resources:
          - com.hxp

#==============================公众号配置==============================
wechat:
  app-id: wxebd55ad16a74cb04
  # 公众号AppSecret
  secret: 044a4443d0bb52de3d6b27303d372a9b
  # 公众号Token
  token: hexp
  # 公众号AES Key
  aesKey: 8F0hMITrdXpjGpccP6JUYwKjGuhaQVnS9yxoCjMRU41

  appletAppId:
  appletSecret:

#==============================豆包推理AI配置=======================================
ai:
  # API Key
  apiKey: sk-ec7978f0874d30dc794e3a904ed3865ff75570b0d89def158bad876110d62aec
  baseUrl: https://ark.cn-beijing.volces.com/api/v3
  # 推理接入点ID
  model:

#==============================邮箱配置=======================================
mail:
  smtp:
    host: smtp.163.com
    port: 25
    email:
    password:

#============================第三方登录配置信息===================================
qq:
  app-id: 102796089
  app-key: lQuCF6lBNK1ThfNq
  redirect-url: https://blog.hexp.online/xuepeng/api/auth/callback/qq

weibo:
  app-id: baafe63e81a615892da03a0d67dcd0c286ce614d5f29da0e5506b0cb52efebef
  app-secret: 61261625cd17b0e4ce3b6cdb3cf0d8897a66ff1a0632d7173fdbb181ecc71929
  redirect-url: https://blog.hexp.online/xuepeng/api/auth/weibo

gitee:
  app-id:
  app-secret: 5392b63abff3f5351bfeddc397911c8b
  redirect-url: https://blog.hexp.online/xuepeng/api/auth/callback/gitee

github:
  app-id: Ov23liQL6H8vYLYu39kc
  app-secret: 66762cf68cbe9d0e111eb67b66bb987f5a715f60
  redirect-url: https://blog.hexp.online/xuepeng/api/auth/callback/github
